services:
  prometheus:
    image: prom/prometheus:latest
    environment:
      - BACKEND_SERVER_URL=http://host.docker.internal:3000
      # - BACKEND_SERVER_URL=http://192.168.3.248:3000
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
    ports:
      - "9090:9090"
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki/:/etc/loki/
        - loki_data:/data
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail/:/etc/promtail/
    command: -config.file=/etc/promtail/config.yaml
    ports:
      - "9080:9080" # Adjust the port as needed
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./grafana/provisioning:/etc/grafana/provisioning
      # - ./grafana/config.ini:/etc/grafana/config.ini
      # - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - BACKEND_SERVER_URL=http://host.docker.internal:3000
      # - BACKEND_SERVER_URL=http://192.168.3.248:3000
    depends_on:
      - prometheus
    ports:
      - "3001:3000"

volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}
