name: Node.js CI with PNPM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name redis-container

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js and PNPM
        uses: pnpm/action-setup@v1
        with:
          version: "latest" # You can specify a specific version if needed

      - run: pnpm install
        # If you need to install Prisma, you can run 'pnpx prisma generate' here
      - run: pnpm test
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          REDIS_PORT: ${{secrets.REDIS_PORT}}
          REDIS_USERNAME: ""
          REDIS_PASSWORD: ""

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js and PNPM
        uses: pnpm/action-setup@v1
        with:
          version: "latest" # You can specify a specific version if needed
      - run: pnpm run build --if-present
