# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name redis-container
        # env:
        #   REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        #   REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ["6.0"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.8.0
      #   with:
      #     mongodb-version: ${{ matrix.mongodb-version }}
      #     mongodb-replica-set: "rs0"

      - run: npm ci
      - run: npx prisma generate
      - run: npm test
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          REDIS_PORT: ${{secrets.REDIS_PORT}}
          REDIS_USERNAME: ""
          REDIS_PASSWORD: ""
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm run build --if-present
